/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_SIMPLE_PHP_YENC_DECODE_H
#define PHP_SIMPLE_PHP_YENC_DECODE_H

extern zend_module_entry simple_php_yenc_decode_module_entry;
#define phpext_simple_php_yenc_decode_ptr &simple_php_yenc_decode_module_entry

#ifdef PHP_WIN32
# define PHP_SIMPLE_PHP_YENC_DECODE_API __declspec(dllexport)
#else
# define PHP_SIMPLE_PHP_YENC_DECODE_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(simple_php_yenc_decode);
PHP_MSHUTDOWN_FUNCTION(simple_php_yenc_decode);
PHP_RINIT_FUNCTION(simple_php_yenc_decode);
PHP_RSHUTDOWN_FUNCTION(simple_php_yenc_decode);
PHP_MINFO_FUNCTION(simple_php_yenc_decode);

ZEND_NAMED_FUNCTION(_wrap_simple_yenc_decode);
#endif /* PHP_SIMPLE_PHP_YENC_DECODE_H */
